title: "Ben Chun Prtfolio"
theme: jekyll-theme-hyde

navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/